# Generated by Django 4.1 on 2022-08-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blogs_model',
        ),
    ]
