# Generated by Django 4.1 on 2022-08-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blogs_blogs_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs_model',
            new_name='BlogModel',
        ),
    ]
